### ISSUE TITLE
Install fail on YF 4.2.0

### ISSUE THREAD

**Issue by echemik** [efernau/Docker-YetiForceCRM#1]
Hi:) Im also familiar with Docker and YF. I try to update this repo and use 4.2.0 (changes in Dockerfile) but it fails, after install I see :

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u_yf_announcement.is_mandatory' in 'field list' Failed to prepare SQL: SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE ((vtiger_crmentity.deleted=0)) AND (`announcementstatus`=:qp0)`

Did you try? Is there something I forget?

**Comment by efernau** [comment]
Hi,  I haven't tried version 4.2 yet. I'm gonna see if I can reproduce the error.

**Comment by efernau** [comment]
I created an update version 4.2.0, it runs.  

Are you using docker-compose?
What kind of system are you using?

`docker version`

**Comment by echemik** [comment]
Thanks for update.

I clone your repo and its the same in the middle of installation, I use docker compose up -d 

I use Ubuntu 16.04 and Docker on it.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u_yf_announcement.is_mandatory' in 'field list' Failed to prepare SQL: SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE ((vtiger_crmentity.deleted=0)) AND (`announcementstatus`=:qp0)

**Comment by efernau** [comment]
Strange, it works for me. 

What docker version do you use? 
Send the output of:  `docker version`

I did not include all PHP REQUIREMENTS.
What you could try to modify the php.ini.  Maybe the mysql. connect_timeout input and execution_time,... for slow systems better more. Look at https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

**Comment by echemik** [comment]
I use Docker version 17.09.0-ce, build afdb6d4.


I try to install it on very good performance server - error appears after 5
seconds install.

If I install it on container only container environment is important.
Version 4.0.0 works, 4.1.0 and 4.2.0 fails.

dnia 15 października 2017 o 21:21:26, Esra Fernau (notifications@github.com)
napisał:

Strange, it works for me.

What docker version do you use?
Send the output of: docker version

I did not include all PHP REQUIREMENTS.
What you could try to modify the php.ini. Maybe the mysql. connect_timeout
input and execution_time,... for slow systems better more. Look at
https://yetiforce.com/en/knowledge-base/documentation/implementer-documentation/item/web-server-requirements

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/efernau/Docker-YetiForceCRM/issues/1#issuecomment-336734690>,
or mute the thread

**Comment by efernau** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/4146#issuecomment-341368755

**Comment by efernau** [comment]
Hello,

don't use YF anymore but i took care that there is a current docker images. fixed the bugs, have fun with new version 4.4.0
