### ISSUE TITLE
Failed to build: Command returned a non-zero code: 100

### ISSUE THREAD

**Issue by Narzard** [efernau/Docker-YetiForceCRM#3]
Here is a dump of the error. Message at the bottom. Ubuntu server 16.04. Any idea on what to do to fix this? Thanks!!

yeti@yetiforce:/yetidocker/Docker-YetiForceCRM-master$ sudo docker-compose up -d                                     Pulling db (mysql:)...
latest: Pulling from library/mysql
a5a6f2f73cd8: Pull complete
936836019e67: Pull complete
283fa4c95fb4: Pull complete
1f212fb371f9: Pull complete
e2ae0d063e89: Pull complete
5ed0ae805b65: Pull complete
0283dc49ef4e: Pull complete
a7e1170b4fdb: Pull complete
88918a9e4742: Pull complete
241282fa67c2: Pull complete
b0fecf619210: Pull complete
bebf9f901dcc: Pull complete
Building yetiforcecrm
Step 1/21 : FROM php:7.1-apache
7.1-apache: Pulling from library/php
a5a6f2f73cd8: Already exists
633e0d1cd2a3: Pull complete
fcdfdf7118ba: Pull complete
4e7dc76b1769: Pull complete
c425447c8835: Pull complete
033380e6e095: Pull complete
13cbf79d7810: Pull complete
3b3aab261548: Pull complete
3a7622312067: Pull complete
da2d6e1ada9a: Pull complete
99036a0780ab: Pull complete
036866b9f082: Pull complete
e4881f72d153: Pull complete
b9052ab1a6d0: Pull complete
Digest: sha256:607903ae110407c15c7efc2ad41d67c2153fecd6f5e2e446f12ffde60a2c6f76
Status: Downloaded newer image for php:7.1-apache
 ---> fb15c7e9713f
Step 2/21 : ENV DOWNLOAD_URL https://github.com/YetiForceCompany/YetiForceCRM/releases/download/4.2.0/YetiForceCRM-4.2.0-complete.zip
 ---> Running in 2cd340b914f9
Removing intermediate container 2cd340b914f9
 ---> 86e6b1642d26
Step 3/21 : ENV DOWNLOAD_FILE YetiForceCRM-4.2.0-complete.zip
 ---> Running in 22d46cc4d15d
Removing intermediate container 22d46cc4d15d
 ---> 4e21d3814eda
Step 4/21 : ENV EXTRACT_FOLDER YetiForceCRM
 ---> Running in bb125f12180e
Removing intermediate container bb125f12180e
 ---> d2f34fab4f0c
Step 5/21 : ENV WWW_FOLDER /var/www/html
 ---> Running in 6ab413b70c1a
Removing intermediate container 6ab413b70c1a
 ---> 9a42ab0a9650
Step 6/21 : ENV WWW_USER www-data
 ---> Running in 36bfdc5e2ecc
Removing intermediate container 36bfdc5e2ecc
 ---> 48cdf1fe7ad0
Step 7/21 : ENV WWW_GROUP www-data
 ---> Running in 11c43f3f1163
Removing intermediate container 11c43f3f1163
 ---> 7468d4bba742
Step 8/21 : RUN apt-get update && apt-get upgrade -y &&     apt-get install -y wget libfreetype6-dev libxml2-dev libjpeg62-turbo-dev libpng12-dev libmcrypt-dev libcurl4-gnutls-dev libpng-dev libssl-dev libc-client2007e-dev libkrb5-dev unzip cron re2c python tree memcached mysql-client php5-mysqlnd
 ---> Running in 07c383ee0ed9
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:2 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [460 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5152 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7089 kB]
Fetched 7860 kB in 14s (542 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mysqlnd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
E: Package 'php5-mysqlnd' has no installation candidate
ERROR: Service 'yetiforcecrm' failed to build: The command '/bin/sh -c apt-get update && apt-get upgrade -y &&     apt-get install -y wget libfreetype6-dev libxml2-dev libjpeg62-turbo-dev libpng12-dev libmcrypt-dev libcurl4-gnutls-dev libpng-dev libssl-dev libc-client2007e-dev libkrb5-dev unzip cron re2c python tree memcached mysql-client php5-mysqlnd' returned a non-zero code: 100

**Comment by marcodepolo** [comment]
Hello, I can confirm the same issue, would appreciate any help

**Comment by efernau** [comment]
Hello,

don't use YF anymore but i took care that there is a current docker images. fixed the bugs, have fun with new version 4.4.0

**Comment by marcodepolo** [comment]
Thanks a lot!
