### ISSUE TITLE
YetiForce install issue (4.4.0 and 5.0.0) 

### ISSUE THREAD

**Issue by ajl-ewp** [efernau/Docker-YetiForceCRM#4]
I've been working on a 5.0.0 container and have been running into problems installing locally (Same as with the other versions I guess, just trying to get 5 working now); however, when I run my containers on a server, the install works just fine for 4.4.0. 

Have you had issues installing while running the containers on localhost, and if so, how do you get around them?

Also, are you planning on building a 5.0.0 container. I know YetiForce themselves haven't shown interest in maintaining containers so you're the last hope.

**Comment by efernau** [comment]
Haven't tried version 5 yet.  But I will provide a container soon.


I can't reproduce your error.  Have no problems on my workstation and server with the 4.2 version.


What kind of bug do you get? which Docker version do you use?

**Comment by ajl-ewp** [comment]
I'm using the latest version on Ubuntu. I think it's just that running the containers on my laptop is super slow, but running them on the server things work fast enough that I can actually see the progress.

After I finish the install process, if I don't get a database permissions error (happens 90% of the time, I can get around this by using root as my user rather than using the "root password"), I don't get to the progress bar, it just hangs there, and if I'm lucky, I can get to the login screen. I've yet to actually be able to log in.

I think I got through the install yesterday, I'll let you know when I boot up today at work. I'd like to have this set up and configured properly before I migrate any company data. Have you had to migrate from a shared hosting solution to containers? Any tips?

**Comment by ajl-ewp** [comment]
Just an update,

While installing 5.0.0 the application forgets the db host name between the configuration for and the detail confirmation page following it. I'm trying to edit the 5.0.0 app itself to fix this error, and submitted an error to YetiForce themselves, but I thought you'd like to know for your container.

I'm using 1and1internet/ubuntu-18-apache-php-7.2 as a base, and modified some of the run commands to suit the new base.
