### ISSUE TITLE
Question about Intl problem (5.0.0)

### ISSUE THREAD

**Issue by fkmurphy** [efernau/Docker-YetiForceCRM#5]
Hello,
I wanted to consult you if I'm doing something wrong. The containers are built correctly (using version 5.0.0) but when entering http://localhost:8000 I have problems with PHP.
The error is something similar to the following:
https://github.com/YetiForceCompany/YetiForceCRM/issues/9482

> PHP Fatal error: Uncaught Error: Class 'Locale' not found in /var/www/html/devyeti/app/Language.php:717\nStack trace:\n#0 /var/www/html/devyeti/app/Controller/Base.php(23): App\Language::initLocale()\n#1 /var/www/html/devyeti/install/views/Index.php(66): App\Controller\Base->__construct()\n#2 /var/www/html/devyeti/install/Install.php(34): Install_Index_View->__construct()\n#3 {main}\n thrown in /var/www/html/devyeti/app/Language.php on line 717

According to the documentation, the extension intl. I replaced the following Dockerfile line:
```
RUN docker-php-ext-configure imap --with-imap-ssl --with-kerberos && \
    docker-php-ext-install soap curl gd zip mbstring intl imap mysqli pdo pdo_mysql gd iconv  opcache   && \
    rm -rf /var/lib/apt/lists/*
```
to:
```
RUN docker-php-ext-configure imap --with-imap-ssl --with-kerberos && \
    docker-php-ext-configure intl --with-kerberos  && \
    docker-php-ext-install soap curl gd zip mbstring intl imap mysqli pdo pdo_mysql gd iconv  opcache   && \
    rm -rf /var/lib/apt/lists/*
```

Sorry for my English, I speak in Spanish.
thank you and regards!

**Comment by efernau** [comment]
fixed in 5.1.0
